# Generated by Django 3.1 on 2022-03-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
