tasks:
  - name: Backend
    init: bash backend.sh
    command: python manage.py runserver
  - name: Frontend
    init: bash frontend.sh
    command: npm start
  
ports:
  - port: 8000
    visibility: public
    onOpen: open-preview
  - port: 3000
    visibility: public
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
