# Generated by Django 3.1 on 2022-03-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_auto_20220329_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='user',
            new_name='player',
        ),
    ]
