# Generated by Django 3.1 on 2022-03-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_auto_20220329_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='player',
            new_name='user',
        ),
    ]
